openbullet/openbullet

OpenBullet/Pages/Main/Runner/Runner.xaml
it's a small bug in the runner UI of BotsSlider
=> Fixing arrows control bug

RuriLib/LoliScript/LoliScript.cs
Loliscript is better readable with a new line ;)
=> LS better readable

OpenBullet/Pages/Main/Configs/ConfigManager.xaml
Well as you can see here the Total Configs was kinda hidden by the search bar which really annoyed most of users so all what I did was moving it a little up so it fits with all kind of resolution, added it inside of a grid for more UI stability.
=> Fixed UI Config Manager Bug

RuriLib/LoliScript/LoliScript.cs
fix for https://github.com/openbullet/openbullet/issues/51
=> Fix Jump if target is in line 1

RuriLib/Blocks/BlockTCP.cs
Some Servers don't show a banner
fixes https://github.com/openbullet/openbullet/issues/56
though i don't love the sleep() i didn't find a better solution
=> Fix TCP Connection if no Data on connect

OpenBullet/Pages/Dialogs/DialogSelectWordlist.xaml, OpenBullet/Pages/Dialogs/DialogSelectWordlist.xaml.cs
=> Temporary WordList/WordList On-The-Fly

OpenBullet/MainWindow.xaml, OpenBullet/MainWindow.xaml.cs
=> Abliltiy to maximize/minimize by double clicking Title bar

OpenBullet/Pages/Main/WordlistManager.xaml, OpenBullet/Pages/Main/WordlistManager.xaml.cs
=> Rescan button over the wordlists manager

OpenBullet/Pages/StackerBlocks/PageBlockFunction.xaml.cs, RuriLib/Blocks/BlockFunction.cs
Thats my first time using visual studio and coding in C#.
These 2 charsets were highly requested and i needed it too so i just made it as best as i could! i was thinking about instead of giving the new charsets random names like ?m i wanted to give them a name of the combined charsets for example ?ud = Uppercase + Digits but i could not do that since it only reads the first string after the question mark.
=> Added 2 new charsets in randomstring function.

RuriLib/Blocks/BlockFunction.cs
Thanks and Credits to LethalLuck from the Openbullet Anomaly Mod for this
=> Add Unescape Function

RuriLib/LoliScript/LoliScript.cs
on manual JUMP and END SCRIPT in debug log
=> Fix shown target Line Number

OpenBullet/Pages/StackerBlocks/PageBlockBypassCF.xaml, RuriLib/Blocks/BlockBypassCF.cs, RuriLib/RuriLib.csproj, RuriLib/packages.config
Switching back to good old leaf.xnet. But with cookie handling fixes.
Though it doesn't work with all sites it's better than the current state.
There is already on open issue over at leaf to fix the non working sites: https://github.com/csharp-leaf/Leaf.xNet/issues/53
=> Change CloudFlare Lib back to Leaf.xNet

RuriLib/Blocks/BlockBypassCF.cs
Backporting https://github.com/openbullet/openbullet/commit/a4fb0f3334bca0755df97be498f60c3e7f104f96#diff-d9125531b761ec8678f86b718b47c42 to leaf cf block
=> Backport CookieDomain fix

OpenBullet/Pages/StackerBlocks/PageBlockBypassCF.xaml, RuriLib/Blocks/BlockBypassCF.cs
=> Add Error on 302 for CF Bypass

RuriLib/Functions/Encoding/Encode.cs
Base64 decode padding calculation error
Fixes #415
=> Fix Base64 Decode Padding

RuriLib/Blocks/BlockFunction.cs, RuriLib/Blocks/BlockUtility.cs, RuriLib/Blocks/SBlockBrowserAction.cs, RuriLib/Models/BotData.cs
=> Added a locker for BotData#Random & improved/optimized RandomString function using RegEx 

OpenBullet/LSDoc.xml, OpenBullet/Views/StackerBlocks/PageBlockParse.xaml, RuriLib/Blocks/BlockParse.cs, RuriLib/Functions/Parsing/Parse.cs
- dot matches line breaks
- case sensitive matching
=> Added support for RegexOptions

OpenBullet/OpenBullet.csproj, OpenBullet/packages.config
Closes #544 
Did some testing yesterday and today debugged selenium in visual studio and didnt found any thrown expections. After that i updated my google chrome and used the beta branch but i still got the same issue referenced above. After updating the chromedriver no more extra google chrome instances were created and everything is working fine now. The updated chromedriver version should fix the issue :)
=> Updated chromedriver to version 81

OpenBullet/ViewModels/ProxyManagerViewModel.cs, OpenBullet/Views/Main/ProxyManager.xaml.cs
I also improved the performance when the numbers of the working, not working and tested proxies are updated.
=> This fixes the issue with number #601

OpenBulletCLI/Program.cs
The project couldn't be built anymore.
=> Fix for a method that was changed in commit 2cab503

OpenBullet/Views/StackerBlocks/PageBlockFunction.xaml.cs, RuriLib/Blocks/BlockFunction.cs
=> Added new gens to randomstring

OpenBulletCLI/Program.cs
https://github.com/openbullet/openbullet/issues/690
=> Fixing issue 690
